### ISSUE TITLE
Highly active tP noted -- Kudos!

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103T-F12-3/main#110]
Guys, it looks like your tP is maintaining a high-level of coding activities so far and all members are actively contributing (as per the [tP Dashboard](https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false)) :+1:

Note: hope you can work together to help less-active team members, if they need help.

Keep up the good work!

**Comment by shiweing** [comment]
Hi Prof, for one of the pull request, 2 of us merged on our local repo before making a PR to the team repo. Now it looks like one of us did not contribute much on the tP Dashboard. 
How should we handle this so our members get the appropriate acknowledgement for their efforts?

**Comment by damithc** [comment]
RepoSense go by the commit author. It is possible for you to provide more information to RepoSense regarding authorship. See under tP instructions for week 10 (it's the last item).
