### ISSUE TITLE
Add xmls files for docs and remove pumls file from the docs

### ISSUE THREAD

**Issue by Yehezkiel01** [AY1920S1-CS2103T-F12-3/main#132]
Everyone will need to suplement their own diagrams with xml files:

- [x] @tanlk99's diagrams

- [x] @shiweing's diagrams

- [x] @e0031374's diagrams

- [x] @Yehezkiel01's diagrams

- [x] @stevenwjy's diagrams

**Comment by e0031374** [comment]
I was unable to find the drawings for ExecutingTagNoteCommand.png and CreatingTagNoteCommand.png on Draw.io and they were not included in PR #136
